language: node_js
node_js: lts/*

install: yarn

cache:
  yarn: true

script: yarn build

after_success:
  - git init
  - git config --global user.name "hezf"
  - git config --global user.email "287645587@qq.com"
  - git add .
  - git commit -m "Automatically update from travis-ci"
  - git push "https://${GITHUB_TOKEN}@${GITHUB_REF}" master:master

branches:
  only:
    - master

